[GPU] Fix linker error in CommandProcessor::RestoreRegisters()
Linking xenia-app on Linux x86-64 with clang-13 fails with:
/usr/bin/x86_64-pc-linux-gnu-ld: bin/Linux/Debug/libxenia-gpu.a(command_processor.o): in function `xe::gpu::CommandProcessor::RestoreRegisters(unsigned int, unsigned int const*, unsigned int, bool)':
/home/liquid/sourcecode/xenia/build/../src/xenia/gpu/command_processor.cc:139: undefined reference to `xe::gpu::RegisterFile::kRegisterCount'

See this reference why static const is used incorrectly here:
https://stackoverflow.com/questions/5391973/undefined-reference-to-static-const-int

Switch to a constexpr here.